# Generated by Django 4.2 on 2023-04-19 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('players', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('dates', models.CharField(max_length=100)),
                ('pools', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('teams', models.ManyToManyField(to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('place', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.pool')),
                ('teams', models.ManyToManyField(to='tournaments.team')),
            ],
        ),
    ]
