# Generated by Django 4.2 on 2023-04-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='numberStr',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
