# Generated by Django 4.2 on 2023-04-20 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_pool_numberstr_alter_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_Team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='score_Team2',
            field=models.IntegerField(default=0),
        ),
    ]
