# Generated by Django 4.2 on 2023-04-21 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='score',
            new_name='name',
        ),
    ]
